In [20]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [21]:
df1 = pd.read_csv("IMDB Dataset.csv")
df1.shape

(50000, 2)

In [22]:
df1.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [23]:
df =df1.head(100)

In [24]:
df.shape

(100, 2)

**Lower case Conversion**

In [25]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [26]:
df['review']= df['review'].str.lower()

In [27]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

**HTML_tag_removel**

In [28]:
# We will use the regex in python 
import re 
 
def remove_html_tag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [29]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [30]:
remove_html_tag(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [31]:
# Lets apply it all over the data 

df['review'] = df['review'].apply(remove_html_tag)

In [32]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

**remove_url**

In [33]:

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [34]:

text1 = 'Check out my youtube https://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

remove_url(text2)

'Check out my linkedin '

**Punctuation handling**

In [36]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [37]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [49]:
def remove_punc(text):
    for char in exclude:
        text = text.replace(char,'')
    return text

In [50]:
text = 'string.With. Punctuation?'

In [51]:
# let's calculate the time as well to remove the punctuation 

start = time.time()
print(remove_punc(text))
time1 = time.time()-start
print(time1*50000)

stringWith Punctuation
0.0

In [52]:
# Another function to remove punctuations 
def remove_punc1(text):
    return text.translate(str.maketrans('','',exclude))

In [53]:
start = time.time()
remove_punc1(text)
time2 = time.time()-start
print(time2*50000)

51.80835723876953

In [54]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [55]:
remove_punc1(df['review'][5])

'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'

In [57]:
remove_punc(df['review'])

0     one of the other reviewers has mentioned that ...
1     a wonderful little production. the filming tec...
2     i thought this was a wonderful way to spend ti...
3     basically there's a family where a little boy ...
4     petter mattei's "love in the time of money" is...
                            ...
95    daniel day-lewis is the most versatile actor a...
96    my guess would be this was originally going to...
97    well, i like to watch bad horror b-movies, cau...
98    this is the worst movie i have ever seen, as w...
99    i have been a mario fan for as long as i can r...
Name: review, Length: 100, dtype: object

**chat_conversion handle**

In [58]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible'
}

{
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

{'FYI': 'For Your Information',
 'ASAP': 'As Soon As Possible',
 'BRB': 'Be Right Back',
 'BTW': 'By The Way',
 'OMG': 'Oh My God',
 'IMO': 'In My Opinion',
 'LOL': 'Laugh Out Loud',
 'TTYL': 'Talk To You Later',
 'GTG': 'Got To Go',
 'TTYT': 'Talk To You Tomorrow',
 'IDK': "I Don't Know",
 'TMI': 'Too Much Information',
 'IMHO': 'In My Humble Opinion',
 'ICYMI': 'In Case You Missed It',
 'AFAIK': 'As Far As I Know',
 'FAQ': 'Frequently Asked Questions',
 'TGIF': "Thank God It's Friday",
 'FYA': 'For Your Action'}

In [67]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [68]:
chat_conversion('Do this work ASAP')

'Do this work As Soon As Possible'

**Incorrect text handling**

In [71]:
from textblob import TextBlob

In [72]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

In [74]:
textBlb = TextBlob(incorrect_text)
textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

**stopwords**

- Why removel of the stop is necessary and why we don't need the stopwords in the sentence for sentiment analysis ??

Ex. I have below sentence to do the sentiment analysis. 

This movie is awesome i loved it. 

only the below words are required to get the sentiment of the this sentence. 

movie awesome loved -----> this shows the positive sentiment. 

Rest all words are stopwords they are just increasing the dimensionality hence need to remove.

In [75]:
from nltk.corpus import stopwords 
import nltk 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [76]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each',
 'few',
 'more',
 'most',
 'other',
 'some',
 'such',
 'no',
 'nor',
 'not',
 'only',
 'own',
 'same',
 'so',
 'than',
 'too',
 'very',
 's',
 't',
 'can',
 'will',
 'just',
 'don',
 "don't",
 'should',
 "should've",
 'now',
 'd',
 'll',
 'm',
 'o',
 're',
 've',
 'y',
 'ain',
 'aren',
 "aren't",
 'couldn',
 "couldn't",
 'didn',
 "didn't",
 'doesn',
 "doesn't",
 'hadn',
 "hadn't",
 'hasn',
 "hasn't",
 'haven',
 "haven't",
 'isn',
 "isn't",
 'ma',
 'mightn',
 "mightn't",
 'mustn',
 "mustn't",
 'needn',
 "needn't",
 'shan',
 "shan't",
 'shouldn',
 "shouldn't",
 'wasn',
 "wasn't",
 'weren',
 "weren't",
 'won',
 "won't",
 'wouldn',
 "wouldn't"]

In [77]:
len(stopwords.words('english'))

179

In [ ]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [83]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [84]:
df['review'].apply(remove_stopwords)

0     one    reviewers  mentioned   watching  1 oz e...
1      wonderful little production.  filming techniq...
2      thought    wonderful way  spend time    hot s...
3     basically there's  family   little boy (jake) ...
4     petter mattei's "love   time  money"   visuall...
                            ...
95    daniel day-lewis    versatile actor alive. eng...
96     guess would    originally going    least two ...
97    well,  like  watch bad horror b-movies, cause ...
98       worst movie   ever seen,  well as,  worst  ...
99        mario fan   long    remember,    fond memo...
Name: review, Length: 100, dtype: object

**Remove Emoji**

In [85]:
import re 
def remove_emoji(text):
    emoji_pattern =re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)

    return emoji_pattern.sub(r'',text)

In [86]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [87]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [88]:
!pip install emoji

Defaulting to user installation because normal site-packages is not writeable
Collecting emoji
  Obtaining dependency information for emoji from https://files.pythonhosted.org/packages/ef/56/4ddf8b36aa4b52077045b17ffb8958f3360b250df4143d1482d9d5bb54d5/emoji-2.14.0-py3-none-any.whl.metadata
  Downloading emoji-2.14.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.0-py3-none-any.whl (586 kB)
   ---------------------------------------- 0.0/586.9 kB ? eta -:--:--
    --------------------------------------- 10.2/586.9 kB ? eta -:--:--
    --------------------------------------- 10.2/586.9 kB ? eta -:--:--
   -- ------------------------------------ 41.0/586.9 kB 326.8 kB/s eta 0:00:02
   ------ -------------------------------- 92.2/586.9 kB 581.0 kB/s eta 0:00:01
   ----------- -------------------------- 174.1/586.9 kB 871.5 kB/s eta 0:00:01
   ----------------- ---------------------- 256.0/586.9 kB 1.0 MB/s eta 0:00:01
   -------------------------- ------------- 389.1/586.9 kB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 501.8/586.9 kB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 586.9/586.9 kB 1.5 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.0

WARNING: There was an error checking the latest version of pip.

In [89]:
import emoji 
print(emoji.demojize('Python is 🔥'))

Python is :fire:

**Tokenization**

1. Using the split function

**Tokenization**

1. Using the split function

**Tokenization**

1. Using the split function

In [6]:
# Word tokenization 

sent1 = 'I am going to Delhi'
sent1.split()

['I', 'am', 'going', 'to', 'Delhi']

In [7]:
# Sentence tokenization 
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [8]:
sent3 = 'I am going to Delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'Delhi!']

2. Tokenization using Regular Expresion

In [9]:
import re 
sent4 = 'I am going to Delhi!'
token = re.findall("[\w]+",sent3)
token

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
C:\Users\yogesh\AppData\Local\Temp\ipykernel_10444\665181392.py:3: SyntaxWarning: invalid escape sequence '\w'
  token = re.findall("[\w]+",sent3)

['I', 'am', 'going', 'to', 'Delhi']

In [96]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

3. Tokenization using NLTK

In [ ]:
from nltk.tokenize import word_tokenize,sent_tokenize 
import nltk 
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [10]:
sent5 = 'I am going to visit Delhi!'
word_tokenize(sent5)

NameError: name 'word_tokenize' is not defined

In [104]:
sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

4. Spacey (Good)

In [3]:
!pip install en_core_web_sm

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement en_core_web_sm (from versions: none)
ERROR: No matching distribution found for en_core_web_sm
WARNING: There was an error checking the latest version of pip.

In [4]:
import spacy 
nlp = spacy.load('en_core_web_sm')

In [14]:
doc1 = nlp(sent1)
doc2 = nlp(sent2)
doc3 = nlp(sent3)
doc4 = nlp(sent4)

In [19]:
doc4

I am going to Delhi!

In [21]:
for token in doc4:
    print(token)

I
am
going
to
Delhi
!

**Stemmer**

In [7]:
!pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\yogesh\appdata\roaming\python\python312\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\yogesh\appdata\roaming\python\python312\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\yogesh\appdata\roaming\python\python312\site-packages (from nltk) (1.1.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\yogesh\appdata\roaming\python\python312\site-packages (from nltk) (2024.9.11)
Requirement already satisfied: tqdm in c:\users\yogesh\appdata\roaming\python\python312\site-packages (from nltk) (4.66.2)
Requirement already satisfied: colorama in c:\users\yogesh\appdata\roaming\python\python312\site-packages (from click->nltk) (0.4.6)

WARNING: There was an error checking the latest version of pip.

In [2]:
import nltk
from nltk.stem.porter import PorterStemmer

In [1]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [3]:
ps = PorterStemmer()

In [4]:
def stem_word(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [6]:
sample = "Walk walks walking walked"
stem_word(sample)

'walk walk walk walk'

In [7]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [8]:
stem_word(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

Now if you look at the above output some of the words are not readable and some letters are missign, so the word is not redable......this can be overcome with the Lemmitization library.

**Lemmatization**

NOTE: Stemming & lamatization are same to retrieve root words but lamatization is worked good. Lamatization is slow & stemming is fast

In [13]:
import nltk 
from nltk.stem import WordNetLemmatizer 
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmitizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words =nltk.word_tokenize(sentence)

for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words 
print("{0:20}{1:20}".format('word','Lemma'))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmitizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\yogesh\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun